Yung-Che/twitter-api-2020

.env.example
.eslintignore
.eslintrc.yml
.gitattributes
Procfile

我增加了ESlint、env.example、未來要部署至Heroku的Profile，ESlint是幫助校正我們語法是能夠一致的

feat: add eslint and env file

---

_helpers.js
middleware/api-auth.js
middleware/api-error-handler.js

新增驗證用的middleware以及錯誤處理的middleware，不過仍須等待使用者註冊登入測試才能確定功能是否完整

feat: add api-auth.js and api-error-handler.js

---

migrations/20190115071420-create-tweet.js
models/like.js
models/reply.js
models/tweet.js
models/user.js

feat: add relationship between user/reply/tweet

---

migrations/20190115071417-create-user.js
migrations/20190115071418-create-followship.js
migrations/20190115071419-create-tweet.js
migrations/20190115071420-create-reply.js
migrations/20190115071421-create-like.js
models/followship.js
models/like.js
models/reply.js
models/user.js

fix: fix native migration problems

---

package-lock.json
package.json
seeders/20220223095011-users-seeder.js

我增加了使用者seeder
- 1個root帳號
- 5個user帳號

add userSeeder

---

seeders/20220223110153-tweets-seeder.js

add tweets-seeder

---

seeders/20220223110153-tweets-seeder.js
seeders/20220223174315-replies-seeder.js

add replies-seeder

---

controllers/user-controller.js
helpers/formdata-check-helper.js
package-lock.json
package.json
routes/apis/index.js

add account registration

---

models/followship.js
models/like.js
models/reply.js
models/tweet.js
models/user.js

fix: disable underscored

---

controllers/followship-controller.js
migrations/20190115071418-create-followship.js
migrations/20190115071421-create-like.js
models/followship.js
models/like.js
routes/apis/modules/users.js
seeders/20220223110153-tweets-seeder.js

1. 修改model和seeder問題，務必要pull
2. 完成追蹤功能
晚點完成取消追蹤

finish postFollow

---

helpers/file-helper.js
package-lock.json
package.json

新增上傳檔案 helper，npm i imgur@1.0.2

add imgur api

---

controllers/followship-controller.js
routes/apis/index.js
routes/apis/modules/followship.js

feat: can cancel followship

---

controllers/followship-controller.js
controllers/like-controller.js
routes/apis/modules/tweet.js

can cancel like

---

controllers/admin-controller.js
middleware/api-auth.js
migrations/20190115071420-create-reply.js
models/reply.js
routes/apis/index.js
routes/apis/modules/admin.js

add del-admin-tweets router v1

---

controllers/reply-controller.js
models/reply.js
models/tweet.js
routes/apis/modules/tweet.js

1. 可以獲取同一個推文下的所有貼文(含推文作者和回覆作者)
2. 通過測試檔案

feat: can get all replies for tweet

---

controllers/admin-controller.js
routes/apis/modules/admin.js

使用 
model.findAll({
where: {}, // where 條件
attribute: []  //指定回傳欄位
})
來找出所有users，並使用attribute來拉出需要的欄位
有通過測試檔

feat: add admin getUsers router

---

controllers/reply-controller.js
routes/apis/modules/tweet.js

feat: add postReplies and delete password on getReplies

---

controllers/admin-controller.js
routes/apis/modules/admin.js

admin 取得推文路由 可以直接在清單上快覽 Tweet 的前 50 個字

feat: add admin-gettweets router

---

controllers/tweet-controller.js
routes/apis/modules/tweet.js

1. 可以瀏覽所有推文(也標記當前使用者所喜歡或者回覆的推文是哪個)
2. 通過驗證

feat: can view all tweets

---

controllers/tweet-controller.js
routes/apis/modules/tweet.js
seeders/20220225192459-remove-like-and-followship.js

1. 添增可以獲取特定推文的資訊(包含回覆、回覆作者、推文作者、該推文是否被目前使用者喜歡或者評論)
2. 增加一個seeder來提升undo的ux
3. 第一條通過測試檔

feat: incr undo-ux for seeder and finish get-tweet api

---

controllers/admin-controller.js
controllers/user-controller.js
routes/apis/index.js
routes/apis/modules/users.js

add userTop router

---

controllers/tweet-controller.js

add post tweet function

---

controllers/user-controller.js

1.  將 getTopUsers API改成以物件傳遞回傳資料(status、message、data)
2. 重構getTopUsers API

refactor: getTopUsers

---

controllers/user-controller.js

fix: fix security problem

---

config/passport.js
controllers/user-controller.js
helpers/bearer-token-helper.js
package-lock.json
package.json
routes/apis/index.js
routes/apis/modules/users.js

refactor: add isExpiredToken to currentUser

---

controllers/temp-controller.js
routes/apis/index.js
routes/apis/modules/users.js

1. 可觀看特定使用者的追隨者清單(會標記每個人是否為目前使用者所追隨的)
2. 測試檔因sequelize舊版外鍵問題，得先更新並另外開分支去處理

add get-followings

---

controllers/temp-controller.js
controllers/user-controller.js
models/like.js
routes/apis/modules/users.js

1. 修正topuser問題
2. 增加get /users/:id/likes

fix a bug and add get-likes function

---

controllers/temp-controller.js
routes/apis/modules/users.js

1. 可獲取指定使用者所回覆的推文(含內容、標記哪些推文是目前使用者喜歡、所回覆過的)
2. 通過測試檔

feat: get-replied_tweets

---

.gitignore
controllers/user-controller.js
helpers/file-helper.js
helpers/formdata-check-helper.js
middleware/multer.js
package-lock.json
package.json
routes/apis/modules/users.js

add user-putUser router

---

controllers/user-controller.js
helpers/file-helper.js

1. 去掉optional chaining operator

refactor imagefilehandler

---

seeders/20220227143603-likes-seeder.js

feat:add likes-seeder

---

helpers/file-helper.js
seeders/20220227173921-followships-seeder.js

remove additional console.log

---

controllers/user-controller.js

modify getTweets

---

controllers/user-controller.js

user-getTweets add isReplied

---

controllers/user-controller.js
routes/apis/modules/users.js

feat: add default image for deleting image

---

controllers/user-controller.js

fix userTop

---

controllers/user-controller.js

1. 修正註冊後帳號的自我介紹為空值
2. 修正getTweets、getUser無法處理找不到對應使用者的錯誤

fix not found problem

---

controllers/reply-controller.js

feat: set maximum to comment

---

helpers/random-time-generator.js
package-lock.json
package.json
seeders/20220223095011-users-seeder.js
seeders/20220223110153-tweets-seeder.js
seeders/20220223174315-replies-seeder.js
seeders/20220227143603-likes-seeder.js
seeders/20220227173921-followships-seeder.js

1. 產生時間隨機產生機，可方便排序時間
2. 源自於CSDN

feat: add randomTime generator

---

controllers/admin-controller.js

add paging to admin/getTweets

---

middleware/api-auth.js
routes/apis/index.js

1. 可以阻擋後台管理員使用前台功能的API
2. 可以通過驗證

refactor: add only-user-use function
